### ISSUE TITLE
Touch feature issue

### ISSUE THREAD

**Issue by james34602** [Helios-vmg/CopperRat#1]
The respond of the app is not my finger position when touch on screen, seems different devices have different coordinate in native activity, my device using Samsung Galaxy Note 4, this issue is very obvious.

Misc: I have add Hanning window before taking DCT, and much improve spectrum clarity.

**Comment by Helios-vmg** [comment]
Oops. It seems I have a bunch of code from February I forgot to commit. Let me know if updating to 7e67761b5f94b8e6d0711433bbe479da40a7a07d fixes the issue.

**Comment by james34602** [comment]
Nice one, it works!
Happy programming!
